// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsTvUskTquvQo5DyrVO3ziH68pVCnxbzM',
    appId: '1:963561773199:web:4d6a9e60c6eb3e333e78fa',
    messagingSenderId: '963561773199',
    projectId: 'suzuisma',
    authDomain: 'suzuisma.firebaseapp.com',
    storageBucket: 'suzuisma.firebasestorage.app',
    measurementId: 'G-LTF3129MPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGW0Yt52Y2xX6feBniMvtdanv1Sg3fFrM',
    appId: '1:963561773199:android:d55b0e633ad731723e78fa',
    messagingSenderId: '963561773199',
    projectId: 'suzuisma',
    storageBucket: 'suzuisma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoS__nXNkgdJJ3yN5q6J6zkWWgCG_BAco',
    appId: '1:963561773199:ios:27ebcc9285860b523e78fa',
    messagingSenderId: '963561773199',
    projectId: 'suzuisma',
    storageBucket: 'suzuisma.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoS__nXNkgdJJ3yN5q6J6zkWWgCG_BAco',
    appId: '1:963561773199:ios:27ebcc9285860b523e78fa',
    messagingSenderId: '963561773199',
    projectId: 'suzuisma',
    storageBucket: 'suzuisma.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsTvUskTquvQo5DyrVO3ziH68pVCnxbzM',
    appId: '1:963561773199:web:f5f7c8bd01322b763e78fa',
    messagingSenderId: '963561773199',
    projectId: 'suzuisma',
    authDomain: 'suzuisma.firebaseapp.com',
    storageBucket: 'suzuisma.firebasestorage.app',
    measurementId: 'G-XQWMY8NGSE',
  );
}
